aws_profile       = "terraform-puc"
aws_region        = "us-east-1"
aws_instance_type = "t2.micro"
prefix            = "infrastructure"
path_private_key  = "..........."
aws_public_key    = "..........."