name: 'Deploy Infrastructure With Terraform'

on:
  workflow_dispatch:

env:
  BACKEND_BUCKET: "app-puc-terraform"
  BACKEND_BUCKET_KEY: "state/terraform.tfstate"
  TF_VAR_aws_region: "us-east-1"
  TF_VAR_aws_public_key: ${{secrets.AWS_PUBLIC_KEY}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

permissions:
  contents: read

jobs:
  Validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
                    -backend-config="bucket=$BACKEND_BUCKET" \
                    -backend-config="key=$BACKEND_BUCKET_KEY" \
                    -backend-config="region=$TF_VAR_aws_region" \
                    -backend-config="encrypt=true"

      - name: Terraform Validate
        run: terraform validate

  Plan:
    name: 'Plan'
    needs: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: | 
          terraform init \
                    -backend-config="bucket=$BACKEND_BUCKET" \
                    -backend-config="key=$BACKEND_BUCKET_KEY" \
                    -backend-config="region=$TF_VAR_aws_region" \
                    -backend-config="encrypt=true"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Plan
        run: terraform plan

  Deploy:
    name: 'Deploy'
    needs: Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
                    -backend-config="bucket=$BACKEND_BUCKET" \
                    -backend-config="key=$BACKEND_BUCKET_KEY" \
                    -backend-config="region=$TF_VAR_aws_region" \
                    -backend-config="encrypt=true"

      - name: Terraform Apply
        run: terraform apply -auto-approve